# These pipeline steps constitute the quality gate for your service within the QA environment.
# Incorporate any necessary additional logic to validate the service's integrity. A failure in
# this pipeline build will prevent further progression to the subsequent stage.

steps:
  - group: "Run quality gates"
    key: quality-gates
    steps:
      - label: ":pipeline: Trigger Elasticsearch E2E tests in QA"
        trigger: elasticsearch-serverless-e2e-tests-qa
        soft_fail: true
        build:
          message: "${BUILDKITE_MESSAGE}"
          commit: "${BUILDKITE_COMMIT}"
          branch: "${BUILDKITE_BRANCH}"
          env:
            IMAGE_OVERRIDE: ""

      - label: ":java: Verify upgrade from current staging"
        command: ".buildkite/scripts/run-gradle.sh bwcTest -Dtests.bwc.tag=current_staging"
        soft_fail: true
        agents:
          provider: "gcp"
          machineType: "n1-standard-16"
          image: family/elasticsearch-ubuntu-2022

      - label: ":kibana: Kibana serverless tests"
        trigger: appex-qa-serverless-kibana-ftr-tests # https://buildkite.com/elastic/appex-qa-serverless-kibana-ftr-tests
        soft_fail: true
        build:
          env:
            ENVIRONMENT: qa
            EC_ENV: qa
            EC_REGION: aws-eu-west-1
            RETRY_TESTS_ON_FAIL: "true"
          message: "${BUILDKITE_MESSAGE} (triggered by Elasticsearch QA quality gate)"
