# These pipeline steps constitute the quality gate for your service within the production environment.
# Incorporate any necessary additional logic to validate the service's integrity. A failure in
# this pipeline build will prevent further progression to the subsequent stage.

steps:
  - label: ":hourglass: Wait 1 hour for environment health metrics"
    if: build.env("ENVIRONMENT") == "production-canary"
    key: production_bake_period
    command:
      - echo "Waiting for 60m for indicative health metrics"
      - sleep ${PROD_CANARY_GATE_WAIT_PERIOD:-3600}

  - label: ":pipeline: Trigger Elasticsearch observability checks in Production"
    if: build.env("ENVIRONMENT") == "production-canary"
    depends_on: production_bake_period
    trigger: serverless-quality-gates
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        TARGET_ENV: production
        CHECK_LOG_ERROR_RATE: true
        MAX_ERROR_PERCENT: 1
        QUERY_WINDOW: 60m
        LOG_LEVEL_ERROR_VALUE: ERROR
        SERVICE: elasticsearch
        SERVICE_REPOSITORY: docker.elastic.co/elasticsearch-ci/elasticsearch-serverless
        SERVICE_VERSION: ${SERVICE_VERSION:0:12}
        SERVICE_TYPE_FIELD: kubernetes.container.name
        CHECK_ELASTICSEARCH_RED_HEALTH_RATE: true
        MAX_ELASTICSEARCH_RED_HEALTH_PERCENT: 1
        CHECK_ALERTS: true
        CHECK_ALERTS_OF_UPDATED_CLUSTERS: true
        CHECK_ALERTS_TRANSIENT_LOOKBACK: 60m
