apiVersion: v1
kind: Service
metadata:
  name: ess-integtest-dev-proxy
  namespace: elastic-system
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: http
    protocol: TCP
    port: 443
    targetPort: 9243
