---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-serverless
  description: Build, test and deploy Elasticsearch Serverless
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-serverless-intake
spec:
  type: buildkite-pipeline
  system: buildkite
  owner: group:elasticsearch-team
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: ':elasticsearch: Build, test and deploy Elasticsearch Serverless'
      name: elasticsearch-serverless / intake
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.intake.yml
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY
      cancel_intermediate_builds: true
      cancel_intermediate_builds_branch_filter: '!main'
      provider_settings:
        build_pull_request_forks: true
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Publish Elasticsearch serverless docker images
  name: buildkite-pipeline-elasticsearch-serverless-publish-docker
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / publish docker
      description: ':docker: buildkite-pipeline-elasticsearch-serverless-publish-docker'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.publish-docker.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Create elasticsearch serverless integration test k8s dev environment
  name: buildkite-pipeline-elasticsearch-serverless-create-k8s-dev
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / create k8s dev
      description: ':k8s: Create elasticsearch serverless integration test k8s dev environment'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.create-k8s-dev.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Delete elasticsearch serverless integration test k8s dev environment
  name: buildkite-pipeline-elasticsearch-serverless-delete-k8s-dev
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / delete k8s dev
      description: ':k8s: Delete elasticsearch serverless integration test k8s dev environment'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.delete-k8s-dev.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Cleanup elasticsearch serverless integration test k8s dev environments
  name: buildkite-pipeline-elasticsearch-serverless-cleanup-k8s-dev
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / cleanup k8s dev
      description: ':k8s: Create elasticsearch serverless integration test k8s dev environment'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.cleanup-k8s-dev.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY
      cancel_intermediate_builds: true
      schedules:
        main_semi_daily:
          branch: 'main'
          cronline: '0 */12 * * *'


---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Deploy Elasticsearch serverless into a k8s dev environment
  name: buildkite-pipeline-elasticsearch-serverless-deploy-dev
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / deploy dev
      description: ':k8s: Deploy Elasticsearch serverless into a k8s dev environment'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.deploy-dev.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Delete Elasticsearch serverless dev deployment
  name: buildkite-pipeline-elasticsearch-serverless-undeploy-dev
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / undeploy dev
      description: ':k8s: Delete Elasticsearch serverless dev deployment'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.undeploy-dev.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Update Elasticsearch serverless dev deployment
  name: buildkite-pipeline-elasticsearch-serverless-update-dev
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / udpate dev
      description: ':k8s: Update Elasticsearch serverless dev deployment'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.update-dev.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Elasticsearch serverless e2e tests on dev
  name: buildkite-pipeline-elasticsearch-serverless-e2e-tests-dev
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / e2e tests dev
      description: ':k8s: Elasticsearch serverless end to end tests'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.e2e-tests-dev.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Elasticsearch serverless e2e tests on QA
  name: buildkite-pipeline-elasticsearch-serverless-e2e-tests-qa
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / e2e tests qa
      description: ':k8s: Elasticsearch serverless E2E tests on QA'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.e2e-tests-qa.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Elasticsearch serverless e2e tests on Staging
  name: buildkite-pipeline-elasticsearch-serverless-e2e-tests-staging
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / e2e tests staging
      description: ':k8s: Elasticsearch serverless E2E tests on Staging'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.e2e-tests-staging.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Validate and update elasticsearch submodule commit
  name: buildkite-pipeline-elasticsearch-serverless-update-submodule
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / update submodule
      description: ':git: Validate and update elasticsearch submodule commit'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.update-submodule.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: BUILD_AND_READ
---

# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Elasticsearch serverless snyk monitoring
  name: buildkite-pipeline-elasticsearch-serverless-snyk-monitoring
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / snyk monitoring
      description: ':gradle: snyk monitoring'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.snyk-monitoring.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY
      schedules:
        Daily:
          branch: main
          cronline: "0 14 * * *"
