---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-serverless
  description: Build, test and deploy Elasticsearch Serverless
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-serverless-intake
spec:
  type: buildkite-pipeline
  system: buildkite
  owner: group:elasticsearch-team
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: ":elasticsearch: Build, test and deploy Elasticsearch Serverless"
      name: elasticsearch-serverless / intake
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.intake.yml
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY
      cancel_intermediate_builds: false
      skip_intermediate_builds: false
      provider_settings:
        trigger_mode: none
        build_branches: true
        build_tags: false
        build_pull_requests: false
        build_pull_request_forks: false
        publish_commit_status: false
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-serverless-intake-trigger
  description: Trigger elasticsearch-serverless-intake pipeline
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-serverless-intake-trigger
spec:
  type: buildkite-pipeline
  system: buildkite
  owner: group:elasticsearch-team
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: Trigger elasticsearch-serverless-intake pipeline
      name: elasticsearch-serverless / intake-trigger
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.intake.trigger.yml
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY
      cancel_intermediate_builds: false
      branch_configuration: "main patch/*"
      provider_settings:
        build_branches: true
        build_tags: false
        build_pull_requests: false
        build_pull_request_forks: false
        publish_commit_status: false
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-serverless-pull-request
  description: Build and test Elasticsearch Serverless for PRs
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-serverless-pull-request
spec:
  type: buildkite-pipeline
  system: buildkite
  owner: group:elasticsearch-team
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: ":elasticsearch: Build and test Elasticsearch Serverless for PRs"
      name: elasticsearch-serverless / pull-request
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.intake.yml
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY
      cancel_intermediate_builds: true
      cancel_intermediate_builds_branch_filter: "!main patch/*"
      provider_settings:
        build_branches: false
        build_tags: false
        build_pull_requests: true
        build_pull_request_forks: true
        publish_commit_status: false
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Publish Elasticsearch serverless docker images
  name: buildkite-pipeline-elasticsearch-serverless-publish-docker
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / publish docker
      description: ":docker: buildkite-pipeline-elasticsearch-serverless-publish-docker"
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.publish-docker.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Deploy Elasticsearch serverless into a k8s qa environment
  name: buildkite-pipeline-elasticsearch-serverless-deploy-qa
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / deploy qa
      description: ":k8s: Deploy Elasticsearch serverless into a k8s qa environment"
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.deploy-qa.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Delete Elasticsearch serverless qa deployment
  name: buildkite-pipeline-elasticsearch-serverless-undeploy-qa
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / undeploy qa
      description: ":k8s: Delete Elasticsearch serverless qa deployment"
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.undeploy-qa.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Update Elasticsearch serverless qa deployment
  name: buildkite-pipeline-elasticsearch-serverless-update-qa
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / update qa
      description: ":k8s: Update Elasticsearch serverless qa deployment"
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.update-qa.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Elasticsearch serverless e2e tests on QA
  name: buildkite-pipeline-elasticsearch-serverless-e2e-tests-qa
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / e2e tests qa
      description: ":k8s: Elasticsearch serverless E2E tests on QA"
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.e2e-tests-qa.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        cloud-tooling:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Elasticsearch serverless e2e tests on Staging
  name: buildkite-pipeline-elasticsearch-serverless-e2e-tests-staging
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / e2e tests staging
      description: ":k8s: Elasticsearch serverless E2E tests on Staging"
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.e2e-tests-staging.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        cloud-tooling:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Validate updated elasticsearch submodule commit
  name: buildkite-pipeline-elasticsearch-serverless-update-submodule
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / validate submodule
      description: ":git: Validate elasticsearch submodule commit"
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.update-submodule.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: BUILD_AND_READ
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Elasticsearch serverless snyk monitoring
  name: buildkite-pipeline-elasticsearch-serverless-snyk-monitoring
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / snyk monitoring
      description: ":gradle: snyk monitoring"
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.snyk-monitoring.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY
      schedules:
        Daily:
          branch: main
          cronline: "0 14 * * *"

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-serverless-quality-gates
  description: Promotion quality gates for serverless Elasticsearch releases
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-serverless-quality-gates
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / quality gates
      description: Promotion quality gates for serverless Elasticsearch releases
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: ./.buildkite/quality-gates/pipeline.quality-gates.yaml
      skip_intermediate_builds: false
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team:
          access_level: MANAGE_BUILD_AND_READ
        enterprise-search:
          access_level: BUILD_AND_READ
        cloud-observability:
          access_level: BUILD_AND_READ
        control-plane-serverless:
          access_level: BUILD_AND_READ
        security-engineering-productivity:
          access_level: BUILD_AND_READ
        fleet:
          access_level: BUILD_AND_READ
        cloud-tooling:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bk-pipeline-elasticsearch-serverless-emergency-quality-gates
  description: Promotion quality gates for emergency serverless Elasticsearch releases
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-serverless-emergency-quality-gates
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / emergency quality gates
      description: Promotion quality gates for emergency serverless Elasticsearch emergency releases
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: ./.buildkite/quality-gates/emergency/pipeline.emergency.quality-gates.yaml
      skip_intermediate_builds: false
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team:
          access_level: MANAGE_BUILD_AND_READ
        enterprise-search:
          access_level: BUILD_AND_READ
        cloud-observability:
          access_level: BUILD_AND_READ
        control-plane-serverless:
          access_level: BUILD_AND_READ
        security-engineering-productivity:
          access_level: BUILD_AND_READ
        fleet:
          access_level: BUILD_AND_READ
        cloud-tooling:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Elasticsearch serverless release promotion
  name: buildkite-pipeline-elasticsearch-serverless-promote-release
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / promote release
      description: ":ship: Promote serverless release"
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.promote-release.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY
      schedules:
        Every Monday at 9am UTC:
          branch: main
          cronline: "0 9 * * 1"

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Elasticsearch serverless emergency release promotion
  name: bk-pipeline-elasticsearch-serverless-promote-emergency-release
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / promote emergency release
      description: ":warning::ship: Promote emergency serverless release"
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.promote-emergency-release.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY
