---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-serverless
  description: Build, test and deploy Elasticsearch Serverless
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-serverless-intake
spec:
  type: buildkite-pipeline
  system: buildkite
  owner: group:elasticsearch-team
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: ':elasticsearch: Build, test and deploy Elasticsearch Serverless'
      name: elasticsearch-serverless / intake
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.intake.yml
      teams:
        elasticsearch-team: {}
        ml-core: {}
        everyone:
          access_level: READ_ONLY
      cancel_intermediate_builds: true
      cancel_intermediate_builds_branch_filter: '!main'
      provider_settings:
        build_pull_request_forks: true
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Publish Elasticsearch serverless docker images
  name: buildkite-pipeline-elasticsearch-serverless-publish-docker
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / publish docker
      description: ':docker: buildkite-pipeline-elasticsearch-serverless-publish-docker'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.publish-docker.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Create elasticsearch serverless integration test gke dev environment
  name: buildkite-pipeline-elasticsearch-serverless-create-gke-dev
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / create gke dev
      description: ':k8s: Create elasticsearch serverless integration test gke dev environment'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.create-gke-dev.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Delete elasticsearch serverless integration test gke dev environment
  name: buildkite-pipeline-elasticsearch-serverless-delete-gke-dev
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / delete gke dev
      description: ':k8s: Delete elasticsearch serverless integration test gke dev environment'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.delete-gke-dev.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        everyone:
          access_level: READ_ONLY

---

# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Cleanup elasticsearch serverless integration test gke dev environments
  name: buildkite-pipeline-elasticsearch-serverless-cleanup-gke-dev
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / cleanup gke dev
      description: ':k8s: Create elasticsearch serverless integration test gke dev environment'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.cleanup-gke-dev.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        everyone:
          access_level: READ_ONLY

---

# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Deploy Elasticsearch serverless into a k8s dev environment
  name: buildkite-pipeline-elasticsearch-serverless-deploy-dev
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / deploy dev
      description: ':k8s: Deploy Elasticsearch serverless into a k8s dev environment'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.deploy-dev.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Delete Elasticsearch serverless dev deployment
  name: buildkite-pipeline-elasticsearch-serverless-undeploy-dev
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / undeploy dev
      description: ':k8s: Delete Elasticsearch serverless dev deployment'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.undeploy-dev.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Elasticsearch serverless end to end tests
  name: buildkite-pipeline-elasticsearch-serverless-e2e-tests
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / e2e tests
      description: ':k8s: Elasticsearch serverless end to end tests'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.e2e-tests.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: Validate and update elasticsearch submodule commit
  name: buildkite-pipeline-elasticsearch-serverless-update-submodule
spec:
  type: buildkite-pipeline
  owner: group:elasticsearch-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-serverless / update submodule
      description: ':git: Validate and update elasticsearch submodule commit'
    spec:
      repository: elastic/elasticsearch-serverless
      pipeline_file: .buildkite/pipeline.update-submodule.yml
      provider_settings:
        trigger_mode: none
      teams:
        elasticsearch-team: {}
        everyone:
          access_level: READ_ONLY

