agents:
  provider: "gcp"
  machineType: "n1-standard-16"
  image: family/elasticsearch-ubuntu-2022

steps:
  - label: ":java: Run serverless Elasticsearch tests"
    command: ".ci/scripts/run-gradle-buildkite.sh check"

  - label: ":s3: Run AWS S3 third party tests"
    command: ".ci/scripts/run-s3-third-party-tests.sh"

  - wait

  - label: ":docker: Publish docker images"
    if: 'build.branch == "main" && build.env("ELASTICSEARCH_SUBMODULE_COMMIT") == null'
    command: ".ci/scripts/publish-docker-artifacts.sh"

  - wait

  - trigger: k8s-gitops-update-image-tag
    label: ":argo: Update gitops image tag"
    if: 'build.branch == "main" && build.env("ELASTICSEARCH_SUBMODULE_COMMIT") == null'
    build:
      env:
        MODE: sed
        TARGET_FILE: elasticsearch-controller.yaml
        IMAGE_TAG: "git-${BUILDKITE_COMMIT:0:12}"
        NAMESPACE: elasticsearch-ci
        IMAGE_NAME: elasticsearch-serverless
        SERVICE: elasticsearch-controller
        COMMIT_MESSAGE: "gitops: update elasticsearch-serverless tag to elastic/elasticsearch-serverless@${BUILDKITE_COMMIT:0:12}"

  - label: ":git: Update elasticsearch submodule commit"
    if: 'build.env("ELASTICSEARCH_SUBMODULE_COMMIT") != null'
    command: ".ci/scripts/update-es-submodule.sh"
