env:
  GPCTL_CONFIG: "https://raw.githubusercontent.com/elastic/serverless-gitops/main/gen/gpctl/elasticsearch/emergency.yaml"

steps:
  - label: ":git: Promote emergency release build"
    command: ".buildkite/scripts/promote-release.sh"
    env:
      USE_GITHUB_CREDENTIALS: "true"
      BLOCK_ON_ISSUES_UNTRIAGED: "false"
      BLOCK_ON_ISSUES_BLOCKER: "false"
    agents:
      image: "docker.elastic.co/ci-agent-images/eck-region/buildkite-agent:1.7"
      memory: "4G"

notify:
  - slack: "#es-serverless-gitops"
    if: (build.branch == "main" || build.branch =~ /^patch\//) && build.state == "failed"
