agents:
  image: "docker.elastic.co/ci-agent-images/eck-region/buildkite-agent:1.4"
  memory: "4G"

env:
  BUILDKITE_DIR: ".buildkite"
  DEPLOY_ID: "${DEPLOY_ID:-integtest-git-${BUILDKITE_COMMIT:0:12}}"
  GCLOUD_PROJECT: "${GCLOUD_PROJECT:-elastic-cloud-dev}"
  GCLOUD_REGION: "${GCLOUD_REGION:-us-central1}"
  GCLOUD_SERVICE_ACCOUNT_VAULT_PATH: "secret/ci/elastic-elasticsearch-serverless/gcloud-integtest-dev-sa"
  GCLOUD_ESS_DEV_NAMESPACE: "${GCLOUD_ESS_DEV_NAMESPACE:-ess-dev-${DEPLOY_ID}}"
  K8S_DEPLOY_ID: ess-dev-${DEPLOY_ID}
  GCS_BUCKET: "${K8S_DEPLOY_ID}-object-store"
  GKE_CLUSTER_NAME: "${GKE_CLUSTER_NAME:-ess-integtest-dev-ci}"
  INTEG_TEST_IMAGE: "docker.elastic.co/elasticsearch-ci/elasticsearch-serverless:${DEPLOY_ID}"
  K8S_DEPLOY_PROJECT_ID: ${K8S_DEPLOY_ID}-project
  VAULT_ADDR: "https://vault-ci-prod.elastic.dev"
  DEPLOY_ARCH: "${DEPLOY_ARCH:-x86_64}"

steps:
  - label: ":docker: Publish docker integ test images"
    trigger: elasticsearch-serverless-publish-docker
    key: docker-publish
    build:
        message: "${BUILDKITE_MESSAGE}"
        commit: "${BUILDKITE_COMMIT}"
        branch: "${BUILDKITE_BRANCH}"
        env:
          DEPLOY_ID: "${DEPLOY_ID}"
          DEPLOY_ARCH: "${DEPLOY_ARCH}"

  - wait: ~
  - label: ":k8s: deploy elasticsearch stateless"
    command: "$$BUILDKITE_DIR/scripts/deploy-ess.sh"