agents:
  provider: k8s
  image: "docker.elastic.co/ci-agent-images/eck-region/buildkite-agent:1.5"
  memory: "4G"

env:
  BUILDKITE_DIR: ".buildkite"
  CI_PIPELINE_ID: "${CI_PIPELINE_ID:-ess-dev-ci}"
  IMAGE_TAG: "git-${BUILDKITE_COMMIT:0:12}"
  DEPLOY_ID: "${DEPLOY_ID:-ess-e2e-ci-${IMAGE_TAG}}"
  CLUSTER_NAME: "${CLUSTER_NAME:-${CI_PIPELINE_ID}}"
  AWS_CLUSTER_NAME: "${CLUSTER_NAME}"
  AWS_REGION: "${AWS_REGION:-eu-west-1}"
  IMAGE_OVERRIDE: "docker.elastic.co/elasticsearch-ci/elasticsearch-serverless:${IMAGE_TAG}"
  VAULT_ADDR: "https://vault-ci-prod.elastic.dev"

steps:
  - label: ":k8s: Undeploy serverless Elasticsearch"
    command: "$$BUILDKITE_DIR/scripts/undeploy-dev.sh"
