env:
  BUILDKITE_DIR: ".buildkite"

steps:
  - label: ":java: Run serverless Elasticsearch functional tests"
    command: ".buildkite/scripts/run-gradle.sh check -Dtests.upgrade.skip=true"
    agents:
      provider: "gcp"
      machineType: "n1-standard-64"
      image: family/elasticsearch-ubuntu-2022
      diskSizeGb: 250
      buildDirectory: /dev/shm/bk
      zones: us-central1-a,us-central1-b,us-central1-c
    env:
      GRADLE_MAX_WORKERS: "10"

  - label: ":s3: Run AWS S3 third party tests"
    command: ".buildkite/scripts/run-s3-third-party-tests.sh"
    agents:
      provider: "gcp"
      machineType: "n1-standard-16"
      image: family/elasticsearch-ubuntu-2022
      diskSizeGb: 250
