env:
  BLOCK_ON_PATCH_BRANCH_NOT_MERGED: ${BLOCK_ON_PATCH_BRANCH_NOT_MERGED:-true}
steps:
  - label: ":git: Promote release build"
    command: ".buildkite/scripts/promote-release.sh"
    env:
      USE_GITHUB_CREDENTIALS: "true"
      BLOCK_ON_ISSUES_UNTRIAGED: "false"
      BLOCK_ON_ISSUES_BLOCKER: "true"
    agents:
      image: "docker.elastic.co/ci-agent-images/eck-region/buildkite-agent:1.7"
      memory: "4G"

notify:
  - slack:
      channels:
        - "#es-serverless-gitops"
    if: (build.branch == "main" || build.branch =~ /^patch\//) && build.state == "failed"
