agents:
  provider: "gcp"
  machineType: "n1-standard-16"
  image: family/elasticsearch-ubuntu-2022

steps:
  - label: ":java: Run serverless Elasticsearch tests"
    command: ".ci/scripts/run-gradle-buildkite.sh check"

  - wait

  - label: ":docker: Publish docker images"
    branches: main
    command: ".ci/scripts/publish-docker-artifacts.sh"

  - wait

  - trigger: k8s-gitops-update-image-tag
    label: ":argo: Update gitops image tag"
    branches: main
    build:
      env:
        MODE: sed
        TARGET_FILE: elasticsearch-controller.yaml
        IMAGE_TAG: "git-${BUILDKITE_COMMIT:0:12}"
        NAMESPACE: elasticsearch-ci
        IMAGE_NAME: elasticsearch-serverless
        SERVICE: elasticsearch-controller
        COMMIT_MESSAGE: "gitops: update elasticsearch-serverless tag to elastic/elasticsearch-serverless@$BUILDKITE_COMMIT"
