env:
  BUILDKITE_DIR: ".buildkite"
  IMAGE_TAG: "git-${BUILDKITE_COMMIT:0:12}"
  DEPLOY_ID: "${DEPLOY_ID:-ess-e2e-ci-${IMAGE_TAG}}"
  VAULT_PATH_API_KEY: "secret/ci/elastic-elasticsearch-serverless/ess-delivery-ci-qa-creds"
  ENV_URL: "https://public-api.qa.cld.elstc.co"
  REGION_ID: "${REGION_ID:-aws-eu-west-1}"
  TEST_ENV: "qa"
  IMAGE_OVERRIDE: "${IMAGE_OVERRIDE-docker.elastic.co/elasticsearch-ci/elasticsearch-serverless:${IMAGE_TAG}}"

steps:
  - label: ":pipeline::arrow_up: E2E tests in ${TEST_ENV}"
    command: "buildkite-agent pipeline upload .buildkite/pipeline.e2e-tests-managed.yml"
    agents:
      image: "docker.elastic.co/ci-agent-images/eck-region/buildkite-agent:1.5"
      memory: "4G"
