env:
  BUILDKITE_DIR: ".buildkite"
  DEPLOY_ID: "${DEPLOY_ID:-ess-e2e-ci-git-${BUILDKITE_COMMIT:0:12}}"
  VAULT_PATH_API_KEY: "secret/ci/elastic-elasticsearch-serverless/ess-delivery-ci-staging-creds"
  ENV_URL: "https://public-api.staging.foundit.no"
  REGION_ID: "aws-us-east-1"
  TEST_ENV: "staging"
  IMAGE_OVERRIDE: ""

steps:
  - label: ":pipeline::arrow_up: E2E tests in ${TEST_ENV}"
    command: "buildkite-agent pipeline upload .buildkite/pipeline.e2e-tests-managed.yml"
    agents:
      image: "docker.elastic.co/ci-agent-images/eck-region/buildkite-agent:1.5"
      memory: "4G"
