agents:
  provider: "gcp"
  machineType: "n1-standard-16"
  image: family/elasticsearch-ubuntu-2022

steps:
  - label: ":java: Running Elasticsearch Stateless 'check' task."
    command: ".ci/scripts/run-gradle-buildkite.sh check"

  - wait

  - label: ":docker: Publish snapshot development artifacts."
    branches: main
    command: ".ci/scripts/publish-docker-artifacts.sh"
