env:
  CI_PIPELINE_ID: "${CI_PIPELINE_ID:-ess-dev-ci}"
  CLUSTER_NAME: "${CLUSTER_NAME:-${CI_PIPELINE_ID}}"
  AWS_CLUSTER_NAME: "${CLUSTER_NAME}"
  AWS_REGION: "${AWS_REGION:-eu-west-1}"
  COSMOSDB_ACCOUNT_NAME: "${COSMOSDB_ACCOUNT_NAME:-serverless-${CI_PIPELINE_ID}}"
  ENV_UNIQUE_NAME: "${ENV_UNIQUE_NAME}"
  GITOPS_PR_COMMIT: ${GITOPS_PR_COMMIT:-HEAD}
  GITOPS_PR_BRANCH: ${GITOPS_PR_BRANCH:-main}
  USER: es-delivery
  DEV_ENV_CSP: "${DEV_ENV_CSP:-aws}"

steps:
  # Delete CI dev env from the pipeline defined in the gitops repo (HEAD)
  - label: ":k8s: :argocd: Delete CI dev environment"
    trigger: k8s-gitops-delete-devenv
    key: delete-devenv
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${GITOPS_PR_COMMIT}"
      branch: "${GITOPS_PR_BRANCH}"
      env:
        AWS_CLUSTER_NAME: "${AWS_CLUSTER_NAME}"
        AWS_REGION: "${AWS_REGION}"
        COSMOSDB_ACCOUNT_NAME: "${COSMOSDB_ACCOUNT_NAME}"
        ENV_UNIQUE_NAME: "${ENV_UNIQUE_NAME}"
        USER: "${USER}"
        DEV_ENV_CSP: "${DEV_ENV_CSP}"
