agents:
  provider: k8s
  image: "docker.elastic.co/ci-agent-images/eck-region/buildkite-agent:1.5"
  memory: "4G"

env:
  BUILDKITE_DIR: ".buildkite"
  PROJECT_ID: "${PROJECT_ID}"
  ESS_API_KEY: "${ESS_API_KEY}"
  CI_PIPELINE_ID: "${CI_PIPELINE_ID:-ess-dev-ci}"
  DEPLOY_ID: "${CI_PIPELINE_ID}-git-${BUILDKITE_COMMIT:0:12}"
  CLUSTER_NAME: "${CLUSTER_NAME:-${CI_PIPELINE_ID}}"
  AWS_CLUSTER_NAME: "${CLUSTER_NAME}"
  AWS_REGION: "${AWS_REGION:-eu-west-1}"
  INTEG_TEST_IMAGE: "docker.elastic.co/elasticsearch-ci/elasticsearch-serverless:${DEPLOY_ID}"
  VAULT_ADDR: "https://vault-ci-prod.elastic.dev"

steps:
  - label: ":docker: Publish docker test images"
    trigger: elasticsearch-serverless-publish-docker
    key: docker-publish
    build:
        message: "${BUILDKITE_MESSAGE}"
        commit: "${BUILDKITE_COMMIT}"
        branch: "${BUILDKITE_BRANCH}"
        env:
          DEPLOY_ID: "${DEPLOY_ID}"

  - wait: ~
  - label: ":k8s: Update elasticsearch stateless"
    command: "$$BUILDKITE_DIR/scripts/update-ess.sh"
