agents:
  provider: "gcp"
  machineType: "n1-standard-16"
  image: family/elasticsearch-ubuntu-2022

env:
  GITOPS_ENV: "${GITOPS_ENV:-dev}"
  GPCTL_CONFIG: "${GPCTL_CONFIG:-https://raw.githubusercontent.com/elastic/serverless-gitops/main/gen/gpctl/elasticsearch/dev.yaml}"

steps:
  - label: ":git: Validate elasticsearch submodule"
    branches: main
    command: ".buildkite/scripts/validate-submodule.sh"

  - label: ":java: Run serverless Elasticsearch functional tests"
    if: build.env('GITOPS_ENV') == 'dev'
    command: ".buildkite/scripts/run-gradle.sh check"

  - label: ":s3: Run AWS S3 third party tests"
    if: build.env('GITOPS_ENV') == 'dev'
    command: ".buildkite/scripts/run-s3-third-party-tests.sh"

  - label: ":docker: Publish docker images"
    key: docker-publish
    cancel_on_build_failing: true
    command: ".buildkite/scripts/publish-docker-artifacts.sh"

  - label: ":rocket: Run E2E tests to check the component update"
    if: build.env('GITOPS_ENV') == 'dev' && build.branch == 'main'
    trigger: service-or-stack-update-e2e-tests
    depends_on: docker-publish
    build:
      env:
        NAMESPACE: elasticsearch-ci
        IMAGE_NAME: elasticsearch-serverless
        IMAGE_TAG: "git-${BUILDKITE_COMMIT:0:12}"

  - label: ":k8s: :java: Run Elasticsearch E2E tests"
    trigger: elasticsearch-serverless-e2e-tests-${GITOPS_ENV}
    branches: main
    depends_on: docker-publish
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        SKIP_DOCKER: "true"

  - wait

  - label: ":argo: Promote build using gpctl"
    trigger: gpctl-promote
    branches: main
    build:
      env:
        REMOTE_SERVICE_CONFIG: $GPCTL_CONFIG
        SERVICE_COMMIT_HASH: $BUILDKITE_COMMIT

  - label: ":git: Push promoted build tags"
    branches: main
    command: ".buildkite/scripts/tag-promoted-commit.sh"
