agents:
  provider: k8s
  image: "docker.elastic.co/ci-agent-images/eck-region/buildkite-agent:1.4"
  memory: "4G"

env:
  CI_PIPELINE_ID: "${CI_PIPELINE_ID:-ess-dev-ci}"
  GCLOUD_PROJECT: "${GCLOUD_PROJECT:-elastic-cloud-dev}"
  GCLOUD_REGION: "${GCLOUD_REGION:-us-central1}"
  GKE_CLUSTER_NAME: "${GKE_CLUSTER_NAME:-${CI_PIPELINE_ID}}"
  COSMOSDB_ACCOUNT_NAME: "${COSMOSDB_ACCOUNT_NAME:-serverless-${CI_PIPELINE_ID}}"
  ENV_UNIQUE_NAME: "${ENV_UNIQUE_NAME}"
  GITOPS_PR_COMMIT: ${GITOPS_PR_COMMIT:-HEAD}
  GITOPS_PR_BRANCH: ${GITOPS_PR_BRANCH:-main}
  USER: es-delivery

steps:
  # Delete CI dev env from the pipeline defined in the gitops repo (HEAD)
  - label: ":k8s: :argocd: Delete CI dev environment"
    trigger: k8s-gitops-delete-devenv
    key: delete-devenv
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${GITOPS_PR_COMMIT}"
      branch: "${GITOPS_PR_BRANCH}"
      env:
        GCLOUD_PROJECT: "${GCLOUD_PROJECT}"
        GCLOUD_REGION: "${GCLOUD_REGION}"
        GKE_CLUSTER_NAME: "${GKE_CLUSTER_NAME}"
        COSMOSDB_ACCOUNT_NAME: "${COSMOSDB_ACCOUNT_NAME}"
        ENV_UNIQUE_NAME: "${ENV_UNIQUE_NAME}"
        USER: "${USER}"
