agents:
  provider: "gcp"
  machineType: "n1-standard-16"
  image: family/elasticsearch-ubuntu-2022

steps:
  - label: ":git: Validate elasticsearch submodule"
    branches: main
    command: ".buildkite/scripts/validate-submodule.sh"

  - label: ":java: Run serverless Elasticsearch tests"
    command: ".buildkite/scripts/run-gradle.sh check"

  - label: ":s3: Run AWS S3 third party tests"
    command: ".buildkite/scripts/run-s3-third-party-tests.sh"

  - label: ":docker: Publish docker images"
    key: docker-publish
    branches: main
    cancel_on_build_failing: true
    command: ".buildkite/scripts/publish-docker-artifacts.sh"

  - label: ":rocket: Run E2E tests to check the component update"
    trigger: service-or-stack-update-e2e-tests
    depends_on: docker-publish
    branches: main
    build:
      env:
        NAMESPACE: elasticsearch-ci
        IMAGE_NAME: elasticsearch-serverless
        IMAGE_TAG: "git-${BUILDKITE_COMMIT:0:12}"
  - wait

  - label: ":argo: Update Image using gpctl with centralized config"
    trigger: gpctl-promote
    branches: main
    build:
      env:
        REMOTE_SERVICE_CONFIG: https://raw.githubusercontent.com/elastic/serverless-gitops/main/gen/gpctl/elasticsearch/config.yaml
        SERVICE_COMMIT_HASH: $BUILDKITE_COMMIT

  - label: ":git: Push promoted build tags"
    branches: main
    command: ".buildkite/scripts/tag-promoted-commit.sh"
