env:
  BUILDKITE_DIR: ".buildkite"
  PROJECT_ID: "${PROJECT_ID}"
  ESS_API_KEY: "${ESS_API_KEY}"
  CI_PIPELINE_ID: "${CI_PIPELINE_ID:-ess-dev-ci}"
  IMAGE_TAG: "git-${BUILDKITE_COMMIT:0:12}"
  DEPLOY_ID: "${CI_PIPELINE_ID}-${IMAGE_TAG}"
  CLUSTER_NAME: "${CLUSTER_NAME:-${CI_PIPELINE_ID}}"
  AWS_CLUSTER_NAME: "${CLUSTER_NAME}"
  AWS_REGION: "${AWS_REGION:-eu-west-1}"
  IMAGE_OVERRIDE: "docker.elastic.co/elasticsearch-ci/elasticsearch-serverless:${IMAGE_TAG}"
  VAULT_ADDR: "https://vault-ci-prod.elastic.dev"

steps:
  - label: ":docker: Publish docker test images"
    trigger: elasticsearch-serverless-publish-docker
    key: docker-publish
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        DEPLOY_ID: "${DEPLOY_ID}"

  - wait: ~
  - label: ":k8s: Update elasticsearch stateless"
    command: "$$BUILDKITE_DIR/scripts/update-ess.sh"
    agents:
      image: "docker.elastic.co/ci-agent-images/eck-region/buildkite-agent:1.5"
      memory: "4G"
