env:
  BUILDKITE_DIR: ".buildkite"
  VAULT_PATH_API_KEY: "secret/ci/elastic-elasticsearch-serverless/ess-delivery-ci-qa-creds"
  ENV_URL: "${ENV_URL:-https://public-api.qa.cld.elstc.co}"
  TEST_ENV: "${TEST_ENV:-qa}"
  PROJECT_TYPE: "${PROJECT_TYPE:-elasticsearch}"

steps:
  - label: ":k8s: Cleanup stale projects in ${TEST_ENV}"
    command: "$BUILDKITE_DIR/scripts/cleanup-managed-projects.sh"
    agents:
      image: "docker.elastic.co/ci-agent-images/eck-region/buildkite-agent:1.5"
      memory: "4G"
    notify:
      - slack: "#es-delivery"
        if: build.state == "failed"
