agents:
  provider: k8s
  image: "docker.elastic.co/ci-agent-images/eck-region/buildkite-agent:1.5"
  memory: "4G"

env:
  MAX_DEPLOYMENT_AGE_IN_HOUR: "${MAX_DEPLOYMENT_AGE_IN_HOUR:-48}"
  BUILDKITE_DIR: ".buildkite"
  CI_PIPELINE_ID: "${CI_PIPELINE_ID:-ess-dev-ci}"
  CLUSTER_NAME: "${CLUSTER_NAME:-${CI_PIPELINE_ID}}"
  AWS_CLUSTER_NAME: "${CLUSTER_NAME}"
  VAULT_ADDR: "https://vault-ci-prod.elastic.dev"

steps:
  - label: ":k8s: cleanup elasticsearch stateless deployments and dev environments"
    command: "$$BUILDKITE_DIR/scripts/cleanup-ess-dev.sh"
