stateless.enabled: true
search.query_phase_parallel_collection_enabled: true
s3.client.default.max_retries: 5
s3.client.backup.max_retries: 9
logger.org.elasticsearch.repositories.s3.S3RequestRetryStats: DEBUG

# allow more concurrent recoveries in serverless, since we wait for object store during recovery.
cluster.routing.allocation.node_concurrent_recoveries: 10
# also raise this for same reason, though we accept that translog replay may take a short while, requiring mainly
# CPU/IO.
cluster.routing.allocation.node_initial_primaries_recoveries: 10
# increase to 5K in serverless. This is not unheard of on frozen, so should work. Also, stats is not available to
# users so we have some control. Finally, if this does not work, we would likely like to investigate it.
cluster.max_shards_per_node: 5000

# TEMPORARY: until CP-3935 is resolved, the controller will force kill nodes shutting down after 10 minutes
# this override temporarily sets the ES timeout to less than 10 minutes so that we ensure (1) that we log that
# we breached the timeout and (2) that the polling aligns so that we don't timeout just before the last
# poll can actually run.
serverless.sigterm.timeout: 590s
serverless.sigterm.poll_interval: 59s
