stateless.enabled: true
search.query_phase_parallel_collection_enabled: true
s3.client.default.max_retries: 5
s3.client.backup.max_retries: 9
logger.org.elasticsearch.repositories.s3.S3RequestRetryStats: DEBUG
